# print("Thick morning mist hangs over the East River, surrounding the Brooklyn Bridge in a grey haze.")
print("A subway train clatters along the high tracks, stirring up the bright streets of Bushwick.")
print("Baristas across Williamsburg pull espresso shots to fuel the early morning rush.")
print("Local muralists shake their spray cans, filling brick facades with brand-new artwork.")
print("In Prospect Park, joggers lap the main meadow while dogs sprint across the grass.")
print("Come afternoon, the smell of brick-oven pizza sweeps through the avenues of DUMBO.")
print("Teenagers gather at neighborhood courts, cheering as a jump shot splashes through the net.")
print("Late sun illuminates the brownstones, casting a warm glow over Brooklyn's quiet avenues.")
print("When night falls, the Coney Island Wonder Wheel lights up the boardwalk near the beach.")
print("The Manhattan skyline sparkles over the water, but the true spirit of the city lives in Brooklyn.")
